# Generated by Django 6.0 on 2025-12-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0003_job_location_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('other', 'Other')], default='junior', max_length=100),
        ),
    ]
